-- Migration: Add purchase_orders table
CREATE TABLE IF NOT EXISTS purchase_orders (
    id INT PRIMARY KEY AUTO_INCREMENT,
    po_number VARCHAR(50) UNIQUE NOT NULL,
    to_supplier VARCHAR(200),
    date DATE,
    phone VARCHAR(20),
    attn VARCHAR(100),
    rab_id INT,
    items JSON,
    projects TEXT,
    material_ref TEXT,
    total DECIMAL(15,2) DEFAULT 0,
    ppn DECIMAL(15,2) DEFAULT 0,
    grand_total DECIMAL(15,2) DEFAULT 0,
    in_words TEXT,
    note TEXT,
    deliver_by DATE,
    deliver_to VARCHAR(200),
    ordered_by VARCHAR(100),
    purchasing VARCHAR(100),
    prepared_by VARCHAR(100),
    approved_by VARCHAR(100) DEFAULT 'Anriko K, ST.',
    term_of_payment VARCHAR(200) DEFAULT 'Anriko K, ST.',
    status VARCHAR(20) DEFAULT 'draft',
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (rab_id) REFERENCES rab(id) ON DELETE SET NULL,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);
